/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
    }
    interface CenterView {
    }
    interface CenterViewInnerContent {
    }
    interface CenterViewRevCounter {
    }
    interface CenterViewRevLimiterGlow {
        "isActive": boolean;
    }
    interface CenterViewRevMarkers {
        "currentValue": number;
    }
    interface CenterViewRevNeedle {
        "currentValue": number;
    }
    interface CenterViewRevShade {
        "currentValue": number;
    }
    interface CenterViewSideGauges {
    }
    interface IntroView {
    }
    interface LeftViewInfo {
    }
    interface MainStatusSymbol {
    }
    interface MainStatusSymbolsLayer {
    }
    interface MainView {
    }
    interface RightViewPageAllinfo {
    }
    interface RightViewPageDiagrams {
    }
    interface RightViewPagePowertraingraph {
    }
    interface RightViewScrollContainer {
    }
    interface WelcomeView {
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLCenterViewElement extends Components.CenterView, HTMLStencilElement {
    }
    var HTMLCenterViewElement: {
        prototype: HTMLCenterViewElement;
        new (): HTMLCenterViewElement;
    };
    interface HTMLCenterViewInnerContentElement extends Components.CenterViewInnerContent, HTMLStencilElement {
    }
    var HTMLCenterViewInnerContentElement: {
        prototype: HTMLCenterViewInnerContentElement;
        new (): HTMLCenterViewInnerContentElement;
    };
    interface HTMLCenterViewRevCounterElement extends Components.CenterViewRevCounter, HTMLStencilElement {
    }
    var HTMLCenterViewRevCounterElement: {
        prototype: HTMLCenterViewRevCounterElement;
        new (): HTMLCenterViewRevCounterElement;
    };
    interface HTMLCenterViewRevLimiterGlowElement extends Components.CenterViewRevLimiterGlow, HTMLStencilElement {
    }
    var HTMLCenterViewRevLimiterGlowElement: {
        prototype: HTMLCenterViewRevLimiterGlowElement;
        new (): HTMLCenterViewRevLimiterGlowElement;
    };
    interface HTMLCenterViewRevMarkersElement extends Components.CenterViewRevMarkers, HTMLStencilElement {
    }
    var HTMLCenterViewRevMarkersElement: {
        prototype: HTMLCenterViewRevMarkersElement;
        new (): HTMLCenterViewRevMarkersElement;
    };
    interface HTMLCenterViewRevNeedleElement extends Components.CenterViewRevNeedle, HTMLStencilElement {
    }
    var HTMLCenterViewRevNeedleElement: {
        prototype: HTMLCenterViewRevNeedleElement;
        new (): HTMLCenterViewRevNeedleElement;
    };
    interface HTMLCenterViewRevShadeElement extends Components.CenterViewRevShade, HTMLStencilElement {
    }
    var HTMLCenterViewRevShadeElement: {
        prototype: HTMLCenterViewRevShadeElement;
        new (): HTMLCenterViewRevShadeElement;
    };
    interface HTMLCenterViewSideGaugesElement extends Components.CenterViewSideGauges, HTMLStencilElement {
    }
    var HTMLCenterViewSideGaugesElement: {
        prototype: HTMLCenterViewSideGaugesElement;
        new (): HTMLCenterViewSideGaugesElement;
    };
    interface HTMLIntroViewElement extends Components.IntroView, HTMLStencilElement {
    }
    var HTMLIntroViewElement: {
        prototype: HTMLIntroViewElement;
        new (): HTMLIntroViewElement;
    };
    interface HTMLLeftViewInfoElement extends Components.LeftViewInfo, HTMLStencilElement {
    }
    var HTMLLeftViewInfoElement: {
        prototype: HTMLLeftViewInfoElement;
        new (): HTMLLeftViewInfoElement;
    };
    interface HTMLMainStatusSymbolElement extends Components.MainStatusSymbol, HTMLStencilElement {
    }
    var HTMLMainStatusSymbolElement: {
        prototype: HTMLMainStatusSymbolElement;
        new (): HTMLMainStatusSymbolElement;
    };
    interface HTMLMainStatusSymbolsLayerElement extends Components.MainStatusSymbolsLayer, HTMLStencilElement {
    }
    var HTMLMainStatusSymbolsLayerElement: {
        prototype: HTMLMainStatusSymbolsLayerElement;
        new (): HTMLMainStatusSymbolsLayerElement;
    };
    interface HTMLMainViewElement extends Components.MainView, HTMLStencilElement {
    }
    var HTMLMainViewElement: {
        prototype: HTMLMainViewElement;
        new (): HTMLMainViewElement;
    };
    interface HTMLRightViewPageAllinfoElement extends Components.RightViewPageAllinfo, HTMLStencilElement {
    }
    var HTMLRightViewPageAllinfoElement: {
        prototype: HTMLRightViewPageAllinfoElement;
        new (): HTMLRightViewPageAllinfoElement;
    };
    interface HTMLRightViewPageDiagramsElement extends Components.RightViewPageDiagrams, HTMLStencilElement {
    }
    var HTMLRightViewPageDiagramsElement: {
        prototype: HTMLRightViewPageDiagramsElement;
        new (): HTMLRightViewPageDiagramsElement;
    };
    interface HTMLRightViewPagePowertraingraphElement extends Components.RightViewPagePowertraingraph, HTMLStencilElement {
    }
    var HTMLRightViewPagePowertraingraphElement: {
        prototype: HTMLRightViewPagePowertraingraphElement;
        new (): HTMLRightViewPagePowertraingraphElement;
    };
    interface HTMLRightViewScrollContainerElement extends Components.RightViewScrollContainer, HTMLStencilElement {
    }
    var HTMLRightViewScrollContainerElement: {
        prototype: HTMLRightViewScrollContainerElement;
        new (): HTMLRightViewScrollContainerElement;
    };
    interface HTMLWelcomeViewElement extends Components.WelcomeView, HTMLStencilElement {
    }
    var HTMLWelcomeViewElement: {
        prototype: HTMLWelcomeViewElement;
        new (): HTMLWelcomeViewElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "center-view": HTMLCenterViewElement;
        "center-view-inner-content": HTMLCenterViewInnerContentElement;
        "center-view-rev-counter": HTMLCenterViewRevCounterElement;
        "center-view-rev-limiter-glow": HTMLCenterViewRevLimiterGlowElement;
        "center-view-rev-markers": HTMLCenterViewRevMarkersElement;
        "center-view-rev-needle": HTMLCenterViewRevNeedleElement;
        "center-view-rev-shade": HTMLCenterViewRevShadeElement;
        "center-view-side-gauges": HTMLCenterViewSideGaugesElement;
        "intro-view": HTMLIntroViewElement;
        "left-view-info": HTMLLeftViewInfoElement;
        "main-status-symbol": HTMLMainStatusSymbolElement;
        "main-status-symbols-layer": HTMLMainStatusSymbolsLayerElement;
        "main-view": HTMLMainViewElement;
        "right-view-page-allinfo": HTMLRightViewPageAllinfoElement;
        "right-view-page-diagrams": HTMLRightViewPageDiagramsElement;
        "right-view-page-powertraingraph": HTMLRightViewPagePowertraingraphElement;
        "right-view-scroll-container": HTMLRightViewScrollContainerElement;
        "welcome-view": HTMLWelcomeViewElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface CenterView {
    }
    interface CenterViewInnerContent {
    }
    interface CenterViewRevCounter {
    }
    interface CenterViewRevLimiterGlow {
        "isActive"?: boolean;
    }
    interface CenterViewRevMarkers {
        "currentValue"?: number;
    }
    interface CenterViewRevNeedle {
        "currentValue"?: number;
    }
    interface CenterViewRevShade {
        "currentValue"?: number;
    }
    interface CenterViewSideGauges {
    }
    interface IntroView {
    }
    interface LeftViewInfo {
    }
    interface MainStatusSymbol {
    }
    interface MainStatusSymbolsLayer {
    }
    interface MainView {
    }
    interface RightViewPageAllinfo {
    }
    interface RightViewPageDiagrams {
    }
    interface RightViewPagePowertraingraph {
    }
    interface RightViewScrollContainer {
    }
    interface WelcomeView {
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "center-view": CenterView;
        "center-view-inner-content": CenterViewInnerContent;
        "center-view-rev-counter": CenterViewRevCounter;
        "center-view-rev-limiter-glow": CenterViewRevLimiterGlow;
        "center-view-rev-markers": CenterViewRevMarkers;
        "center-view-rev-needle": CenterViewRevNeedle;
        "center-view-rev-shade": CenterViewRevShade;
        "center-view-side-gauges": CenterViewSideGauges;
        "intro-view": IntroView;
        "left-view-info": LeftViewInfo;
        "main-status-symbol": MainStatusSymbol;
        "main-status-symbols-layer": MainStatusSymbolsLayer;
        "main-view": MainView;
        "right-view-page-allinfo": RightViewPageAllinfo;
        "right-view-page-diagrams": RightViewPageDiagrams;
        "right-view-page-powertraingraph": RightViewPagePowertraingraph;
        "right-view-scroll-container": RightViewScrollContainer;
        "welcome-view": WelcomeView;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "center-view": LocalJSX.CenterView & JSXBase.HTMLAttributes<HTMLCenterViewElement>;
            "center-view-inner-content": LocalJSX.CenterViewInnerContent & JSXBase.HTMLAttributes<HTMLCenterViewInnerContentElement>;
            "center-view-rev-counter": LocalJSX.CenterViewRevCounter & JSXBase.HTMLAttributes<HTMLCenterViewRevCounterElement>;
            "center-view-rev-limiter-glow": LocalJSX.CenterViewRevLimiterGlow & JSXBase.HTMLAttributes<HTMLCenterViewRevLimiterGlowElement>;
            "center-view-rev-markers": LocalJSX.CenterViewRevMarkers & JSXBase.HTMLAttributes<HTMLCenterViewRevMarkersElement>;
            "center-view-rev-needle": LocalJSX.CenterViewRevNeedle & JSXBase.HTMLAttributes<HTMLCenterViewRevNeedleElement>;
            "center-view-rev-shade": LocalJSX.CenterViewRevShade & JSXBase.HTMLAttributes<HTMLCenterViewRevShadeElement>;
            "center-view-side-gauges": LocalJSX.CenterViewSideGauges & JSXBase.HTMLAttributes<HTMLCenterViewSideGaugesElement>;
            "intro-view": LocalJSX.IntroView & JSXBase.HTMLAttributes<HTMLIntroViewElement>;
            "left-view-info": LocalJSX.LeftViewInfo & JSXBase.HTMLAttributes<HTMLLeftViewInfoElement>;
            "main-status-symbol": LocalJSX.MainStatusSymbol & JSXBase.HTMLAttributes<HTMLMainStatusSymbolElement>;
            "main-status-symbols-layer": LocalJSX.MainStatusSymbolsLayer & JSXBase.HTMLAttributes<HTMLMainStatusSymbolsLayerElement>;
            "main-view": LocalJSX.MainView & JSXBase.HTMLAttributes<HTMLMainViewElement>;
            "right-view-page-allinfo": LocalJSX.RightViewPageAllinfo & JSXBase.HTMLAttributes<HTMLRightViewPageAllinfoElement>;
            "right-view-page-diagrams": LocalJSX.RightViewPageDiagrams & JSXBase.HTMLAttributes<HTMLRightViewPageDiagramsElement>;
            "right-view-page-powertraingraph": LocalJSX.RightViewPagePowertraingraph & JSXBase.HTMLAttributes<HTMLRightViewPagePowertraingraphElement>;
            "right-view-scroll-container": LocalJSX.RightViewScrollContainer & JSXBase.HTMLAttributes<HTMLRightViewScrollContainerElement>;
            "welcome-view": LocalJSX.WelcomeView & JSXBase.HTMLAttributes<HTMLWelcomeViewElement>;
        }
    }
}
